In [6]:
import numpy as np

arr = np.arange(0, 11)
arr + arr # addition
arr * arr
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [10]:
arr / arr
# 0/0 gives a warning please remember => nan

1 / arr
# 1/0 gives also the warning => inf

C:\Users\vasud\AppData\Local\Temp\ipykernel_15264\1980280538.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr
C:\Users\vasud\AppData\Local\Temp\ipykernel_15264\1980280538.py:4: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
np.max(arr)
np.sin(arr)
np.log(arr)
np.sqrt(arr)
 
# universal array funcitons.

C:\Users\vasud\AppData\Local\Temp\ipykernel_15264\2357630763.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])