In [6]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d.shape

arr_2d[1][2]
arr_2d[2,2]

9

In [9]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr = np.arange(1,11)
arr

bool_arr = arr > 5
arr[arr > 5]
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [21]:
arr = np.arange(50).reshape(5, 10)
arr
arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])