In [2]:
import numpy as np

arr = np.arange(0, 11)
arr
arr[8]
arr[2:8]
arr[-2:]

array([ 9, 10])

In [8]:
# similar to list, but the differnce is broadcasting

arr[1:8] = 100
arr

# the slice returns a view of the actual array, nt the copy, due to memroy issue if the array size is large
arr_slice = arr[:]
arr_slice
arr_slice[1:4] = 9999
arr_slice

arr

array([   0, 9999, 9999, 9999,  100,  100,  100,  100,    8,    9,   10])

In [11]:
# therefore if you want copy
arr_copy = arr.copy()
arr_copy[1:3] = 88888
arr_copy
arr

array([   0, 9999, 9999, 9999,  100,  100,  100,  100,    8,    9,   10])